src/main/java/hermes/web/Bean.java
package hermes.web;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.primefaces.context.RequestContext;

import hermes.dominio.EstadoPedido;
import hermes.dominio.Pedido;
import hermes.dominio.Producto;
import hermes.logica.ServicioPedido;



public class Bean {
	private ServicioPedido servicio;
	private Pedido pedidosHistoricosSeleccionado;
	private boolean noHaySeleccionado;
	private EstadoPedido estado;
	
	
	 
	 public void addMessage(String summary, String detail) {
	        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary, detail);
	        FacesContext.getCurrentInstance().addMessage(null, message);
	    }
}

src/main/java/hermes/web/OrderController.java
package hermes.web;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import Utilidades.Respuesta;
import hermes.dominio.Cancelacion;
import hermes.dominio.Pedido;
import hermes.logica.OrderService;

@RestController
@RequestMapping("/pedido")
@CrossOrigin(origins = "*")
public class OrderController {

	@Autowired
	private OrderService _service;
	
	// CALL CONSULTAS
	@GetMapping
	public Page<Pedido> getAllPedidos(Pageable page) {
		return _service.listarTodosPedidos(page);
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public Pedido getOnePedido(@PathVariable(name = "id") Long id) {
		return _service.obtenerPedido(id);
	}
		
	// ALTA
	@PostMapping
	public Respuesta registrarOrdenDeServicio(@RequestBody Pedido pedido) {
		return _service.registraPedido(pedido);
	}
	
	// MODIFICACIÓN
    @RequestMapping(value = "/{id}" , method = RequestMethod.PUT)
    public Respuesta modificaPedido(@RequestBody Pedido pedido, @PathVariable(name = "id") Long id) {
    	return _service.modificarPedido(id, pedido);
    }
	
	// CAMBIO ESTADOS
    @RequestMapping(value = "/cancelar" , method = RequestMethod.PUT)
    public Respuesta cancelarPedido(@RequestBody Cancelacion cancelacion) {
    	return _service.cancelar(cancelacion);
    }
    
    @RequestMapping(value = "/detalle/cancelar" , method = RequestMethod.PUT)
    public Respuesta cancelarDetalle(@RequestBody Cancelacion cancelacion) {
    	return _service.cancelar(cancelacion);
    }
}

src/main/java/hermes/web/ProductController.java
package hermes.web;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;

import hermes.dominio.Producto;
import hermes.logica.ProductService;


@RestController
@RequestMapping("/producto")
@CrossOrigin(origins = "*")
public class ProductController {

	@Autowired
	private ProductService _service;
	
	// CALL CONSULTAS
	@GetMapping
	public List<Producto> getAllPrductos(){
		return _service.listarTodosProductosHabilitados();
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public Producto getPrducto(@PathVariable(name = "id") Integer id){
		try {
			return _service.obtenerProducto(id);
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	@RequestMapping(value = "/listar/{idTipo}", method = RequestMethod.GET)
	public List<Producto> getPrductosPorTipoProducto(@PathVariable(name = "idTipo") Integer idTipo){
		try {
			return _service.getPrductosPorTipoProducto(idTipo);
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}
	}
	
}

src/main/java/hermes/web/SucursalController.java
package hermes.web;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import hermes.dominio.Sucursal;
import hermes.logica.BranchService;

@RestController
@RequestMapping("/sucursal")
@CrossOrigin(origins = "*")
public class SucursalController {

	@Autowired
	private BranchService _servicio;
	
	// CALL CONSULTAS
	@GetMapping
	public List<Sucursal> getAllSucursales(){
		return _servicio.listarTodasSucursales();
	}

	@RequestMapping(value = "/habilitadas", method = RequestMethod.GET)
	public List<Sucursal> getSucursalesHabilitadas(){
		return _servicio.listarTodasHabilitadas();
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public Sucursal getSucursal(@PathVariable(name = "id") Integer id){
		return _servicio.obtenerSucursalSinGeolocalizacion(id);
	}
}

src/main/java/hermes/web/SupportController.java
package hermes.web;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import hermes.dominio.TipoEntrega;
import hermes.dominio.TipoPago;
import hermes.logica.SupportService;

@RestController
@RequestMapping("/soporte")
@CrossOrigin(origins = "*")
public class SupportController {
	@Autowired
	private SupportService _servicio;
	
	//CALL CONSULTAS 
	//TipoEnvio
	@RequestMapping(value = "/tipoentrega", method = RequestMethod.GET)
	public List<TipoEntrega> getAllHabilitadosTipoEntrega(){
		return _servicio.listarTodosHabilitadosTipoEntrega(); 
	}
	
	@RequestMapping(value = "/tipoentrega/{id}", method = RequestMethod.GET)
	public Object getOneTipoEnvio(@PathVariable(name = "id") Integer id){
		if(!id.equals(0))	return _servicio.obtenerTipoEntrega(id);
		else return _servicio.listarTodosTipoEntrega();
	}
	
	//TipoPago
	@RequestMapping(value = "/tipopago", method = RequestMethod.GET)
	public List<TipoPago> getAllHabilitadosTipoPago(){
		return _servicio.listarTodosHabilitadosTipoPago(); 
	}
	
	@RequestMapping(value = "/tipopago/{id}", method = RequestMethod.GET)
	public Object getOneTipoPago(@PathVariable(name = "id") Integer id){
		if(!id.equals(0))	return _servicio.obtenerTipoPago(id);
		else return _servicio.listarTodosTipoPago();
	}
}

src/main/java/hermes/web/TypeProductController.java
package hermes.web;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import hermes.dominio.TipoProducto;
import hermes.logica.ProductService;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping("/tipoproducto")
public class TypeProductController {
	
	@Autowired
	private ProductService _servicio;
	
	// CALL CONSULTAS
	@GetMapping
	public List<TipoProducto> getAllTipoPrductos(){
		return _servicio.listarTodosTipoProductoHabilitados();
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public TipoProducto getTipoPrducto(@PathVariable(name = "id") Integer id){
		try {
			System.out.println(id);
			return _servicio.obtenerTipoProducto(id);
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}
	}
	
}

src/main/webapp/archivo.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:pe="http://primefaces.org/ui/extensions">
<h:head>
	<title>Hermes</title>
	<meta charset="utf-8"></meta>
	<!-- Custom Fonts -->
	<link href="../../resources/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<script src="http://maps.google.com/maps/api/js?key=AIzaSyDjohQyH-_vKzHIXh2x7ImjCGFAIAn55k0"
		type="text/javascript">
	</script>
	
	<script type="text/javascript">
		function geocode() {
			var adrees = $('#formNueva\\:calle').val() + " "
					+ $('#formNueva\\:num').val();
			PF('geoMap').geocode(adrees);
		}
	</script>

</h:head>
<h:body>

	<h:form style="disabled:true;" id="formNueva">
		<h:outputLabel for="calle" value="Calle:" />
		<p:inputText id="calle" value="#{sucursalView.calle}" required="true"
			requiredMessage="Calle no ingresada" />
		<p:message for="calle" display="icon" />
		<h:outputLabel for="num" value="Número:" />
		<p:inputMask id="num" value="#{sucursalView.numero}" required="true"
			requiredMessage="Número no ingresado">
			<f:validateDoubleRange minimum="0.0" />
		</p:inputMask>
		<p:message for="num" display="icon" />
		<h:panelGrid columns="3" style="margin-bottom:10px" cellpadding="5">
			<p:outputLabel for="address" value="Address:" />
			<p:inputText id="address" />
			<p:commandButton value="Geocode" icon="ui-icon-search"
				onclick="geocode(); PF('dlg').show();" type="button" />
		</h:panelGrid>
	</h:form>

		<p:dialog id="gmapDialog" widgetVar="dlg" width="625" height="400"
			modal="true">
				<h:form>
			<p:gmap id="geoGmap" widgetVar="geoMap"
				center="#{geocodeView.centerGeoMap}" zoom="6" type="ROADMAP"
				model="#{geocodeView.geoModel}" style="width:100%;height:400px">
				<p:ajax event="geocode" listener="#{geocodeView.onGeocode}"
					update="@this" />
			</p:gmap>
				</h:form>
		</p:dialog>

</h:body>
</html>

src/main/webapp/index.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Hermes</title>
	<h:outputStylesheet library="css" name="principal.css" />
	<h:outputStylesheet library="css" name="style.css" />
</h:head>
<h:body>

	<p:growl id="growl" sticky="true" showDetail="true" life="3000" />

	<p:layout fullPage="true" widgetVar="layoutWdgt">
		<p:layoutUnit id="header" position="north" size="150">
			<div id="o-wrapper" class="o-wrapper">
				<main class="o-content">
				<div class="o-container">
					<div class="c-buttons">
						<p:commandButton id="c-button--slide-right"
							icon="fa fa-fw fa-shopping-cart" type="button"></p:commandButton>
					</div>
				</div>
				</main>
			</div>
			<h:form id="formIndex">
				<p:commandLink value="Login" onclick="PF('dlg').show();"
					title="login">
					<h:outputText value="Login" />
				</p:commandLink>
			</h:form>
		</p:layoutUnit>

		<p:layoutUnit position="west">
			<div class="menu">
				<!-- <img class="mipedido" src="resources/imagenes/menu3.jpg" /> -->
				<h:form>
					<p:menu model="#{menuView.model}" />
				</h:form>
			</div>
		</p:layoutUnit>

		<p:layoutUnit position="center">
			<h:form id="formProducto">
				<p:dataGrid var="producto" value="#{dataScrollerView.productos}"
					columns="3" layout="grid">
					<div class="contenedor" style="position: relative; height: 165px;">
						<p:panel>
							<h:panelGrid columns="2" style="width:100%; padding: 0.5em 1em;">
								<h:panelGrid columns="1" style="width:100%">
									<h:outputText style="font-size:80%;"
										value="#{producto.tipoProducto.nombre}" />
									<h:outputText value="#{producto.nombre}" />
								</h:panelGrid>

								<h:outputText id="precio" value="#{producto.precio}$" />
							</h:panelGrid>

							<h:panelGrid columns="1" style="width:100%; padding: 0.5em 1em;"> 
								<h:outputText style="font-size: x-small;"
									value="#{producto.descripcion}" />
							</h:panelGrid>
							
							
							<p:commandButton value="Agregar"
								actionListener="#{carritoView.productoSeleccionado(producto)}"
								update=":dlgDetalle" style="width: 100%;"
								styleClass="btnAgregar" />
						</p:panel>
					</div>
				</p:dataGrid>
			</h:form>
		</p:layoutUnit>
	</p:layout>

	<nav id="c-menu--slide-right" class="c-menu c-menu--slide-right">
		<button class="c-menu__close">Ocultar</button>
	
	<h:form id="formPedido">

			<p:growl id="growlCarrito" life="2000" />
			<p:outputPanel id="panelCarrito" rendered="#{carritoView.carrito}"
				autoUpdate="true">
				<p:dataList value="#{carritoView.detalle}" var="detalle"
					type="unordered" itemType="none" emptyMessage="">

					<h:panelGrid columns="4">
						<h:outputText id="cantidad" value="#{detalle.cantidad}x"
							styleClass="cantidadCarrito" />
						<h:panelGrid>
							<h:outputText value="#{detalle.producto.tipoProducto.nombre}"
								styleClass="productoCarrito" />
							<h:outputText value="#{detalle.producto.nombre}"
								styleClass="productoCarrito" />
						</h:panelGrid>
						<h:outputText value="#{detalle.subtotal}$"
							styleClass="subtotalCarrito" />
						<h:panelGrid>
							<p:commandLink update=":dlgModificarDetalle, :formPedido"
								oncomplete="PF('dlgModificarDetalle').show()" title="Editar"
								styleClass="ui-icon ui-icon-pencil">
								<f:setPropertyActionListener value="#{detalle}"
									target="#{carritoView.detalleAModificar}" />
							</p:commandLink>

							<p:commandLink update=":formPedido" title="Eliminar"
								styleClass="ui-icon ui-icon-close"
								style="float:right;margin-right:10px;vertical-align: text-top;">
								<f:setPropertyActionListener value="#{detalle}"
									target="#{carritoView.detalleAEliminar}" />
							</p:commandLink>
						</h:panelGrid>
					</h:panelGrid>

					<p:separator />
				</p:dataList>

				<div id="bottom">
					<div id="bottom-contenido">

						<h:panelGrid id="panelTotal" columns="2"
							style="margin-right: 0px;">
							<p:outputLabel for="total" value="Total: " />
							<p:outputLabel id="total" value="#{carritoView.total}" />
						</h:panelGrid>

						<p:commandButton id="btnConfirmar" value="Confirmar"
							actionListener="#{carritoView.revisarConfirmacion}"
							update=":formPedido, :dlgComprobante, growlCarrito">
							<p:confirm header="Realizar encargo"
								message="De realizar la confirmación, se realizará el encargo de su Orden, ¿quiere revisar su Orden antes de confirmarla?"
								icon="ui-icon-alert" />
							<p:confirmDialog global="true" showEffect="fade"
								hideEffect="fade">
								<p:commandButton value="Revisar Pedido"
									styleClass="ui-confirmdialog-yes" icon="ui-icon-document"
									update=":formPedido, growlCarrito, :dlgComprobante" />
								<p:commandButton value="Volver a la selección de Productos"
									type="button" styleClass="ui-confirmdialog-no"
									icon="ui-icon-close" />
							</p:confirmDialog>
						</p:commandButton>

					</div>
				</div>
			</p:outputPanel>

		</h:form>
	</nav>

	<div id="c-mask" class="c-mask"></div>
	<p:dialog header="Login" widgetVar="dlg" id="dlgLogin"
		resizable="false" closeOnEscape="true" modal="true" showEffect="fade"
		hideEffect="fade" draggable="false">

		<form action="${request.contextPath}/appLogin" method="POST">
			<div class="imgcontainer">
				<img src="resources/imagenes/avatar.png" alt="Avatar" class="avatar" />
			</div>
			<h:outputLabel value="Usuario:" />
			<input type="text" name="app_username" placeholder="Ingrese usuario"
				class="inputLogin" /><br /> <br />
			<h:outputLabel value="Contraseña:" />
			<input type="password" name="app_password"
				placeholder="Ingrese contraseña" class="inputLogin" /> <br /> <a
				onclick="PF('dlgReestablecerPassword').show();"
				id="lnkReestablecerPass">¿Olvidaste tu Usuario o Contraseña?</a> <br />
			<input id="btnLogin" type="submit" value="Login" />

		</form>


	</p:dialog>

	<p:dialog id="dlgDetalle" header="Detalle" widgetVar="dlgDetalle"
		resizable="false" modal="true" closable="false">
		<h:form id="formDetalle">

			<h:panelGrid id="panelDetalle" columns="1">
				<p:outputLabel
					value="#{carritoView.producto.tipoProducto.nombre}: #{carritoView.producto.nombre}" />

				<h:panelGrid id="panelCantidad" columns="3">
					<p:outputLabel value="Cantidad: " for="spinnerCantidad" />
					<p:spinner id="spinnerCantidad" value="#{carritoView.cantidad}"
						min="1" max="10" size="8" />

				</h:panelGrid>
			</h:panelGrid>

			<h:panelGrid id="panelBotones" columns="2">
				<p:commandButton value="Agregar" id="btnAgregar"
					actionListener="#{carritoView.agregarACarrito}"
					update=":dlgDetalle, :formPedido:panelTotal, :formPedido, :formPedido:panelCarrito">
				</p:commandButton>
				<p:commandButton value="Cancelar" id="btnCancelar"
					oncomplete="PF('dlgDetalle').hide();"
					styleClass="ui-priority-primary" process="@this">
				</p:commandButton>
			</h:panelGrid>
		</h:form>
	</p:dialog>
	<p:dialog id="dlgModificarDetalle" header="Detalle"
		widgetVar="dlgModificarDetalle" resizable="false" modal="true"
		closable="false">
		<h:form id="formModificarDetalle">

			<h:panelGrid id="panelModificarDetalle" columns="1">
				<p:outputLabel
					value="#{carritoView.producto.tipoProducto.nombre}: #{carritoView.detalleAModificar.producto.nombre}" />

				<h:panelGrid id="panelModificarCantidad" columns="2">
					<p:outputLabel for="spinnerCantidadMod" value="Cantidad:" />
					<p:spinner id="spinnerCantidadMod"
						value="#{carritoView.detalleAModificar.cantidad}" min="1" max="10"
						size="8" />

				</h:panelGrid>
			</h:panelGrid>

			<h:panelGrid id="panelBotones" columns="2">
				<p:commandButton value="Agregar" id="btnAgregar"
					actionListener="#{carritoView.modificarCarrito}"
					update=":dlgDetalle , :dlgModificarDetalle">
				</p:commandButton>
				<p:commandButton value="Cancelar" id="btnCancelar"
					oncomplete="PF('dlgModificarDetalle').hide();"
					styleClass="ui-priority-primary" process="@this">
				</p:commandButton>
			</h:panelGrid>
		</h:form>
	</p:dialog>

	<p:dialog id="dlgComprobante" header="Resumen del Pedido"
		widgetVar="dlgComprobante" resizable="false" modal="true"
		closable="false">
		<h:form id="formComprobante">
			<p:dataTable class="dataTabla" value="#{carritoView.detalle}"
				var="detalle">
				<f:facet name="header">
            	Comprobación de Pedido
        	</f:facet>
				<p:column headerText="Nombre de tipo de producto" id="nombreTPDT">
					<h:outputText value="#{detalle.nombreTipoProducto}" />
				</p:column>
				<p:column headerText="Nombre de producto" id="nombrePDT">
					<h:outputText value="#{detalle.nombreProducto}" />
				</p:column>
				<p:column headerText="Cantidad" id="cantidadDT">
					<h:outputText value="#{detalle.cantidad}" />
				</p:column>
				<p:column id="subtotalDT">
					<h:outputText value="#{detalle.subtotal}">
						<f:convertNumber type="currency" currencySymbol="$" />
					</h:outputText>
				</p:column>
				<p:columnGroup type="footer">
					<p:row>
						<p:column colspan="3" style="text-align:right" footerText="Total:" />
						<p:column footerText="#{carritoView.total}" />
					</p:row>
				</p:columnGroup>

			</p:dataTable>
			<h:panelGrid columns="2">
			<p:selectOneMenu id="menuSucursales"
				value="#{carritoView.sucursalSeleccionada}"
				style="margin-right:0px;" required="true" name="Sucursales"
				requiredMessage="Sucursal no ingresada">
				<f:selectItem itemLabel="Seleccione una sucursal" itemValue=""
					noSelectionOption="true" />
				<f:selectItems value="#{carritoView.sucursalesHabilitadas}" />
			</p:selectOneMenu>
			<p:message for="menuSucursales" display="icon" />
			</h:panelGrid>
			<h:panelGrid id="panelBotones" columns="2">
				<p:commandButton value="Confirmar" id="btnConfirmarFunca"
					icon="ui-icon-check" styleClass="ui-priority-primary"
					action="#{carritoView.confirmar}"
					update=":formPedido, :formPedido:growlCarrito">
				</p:commandButton>

				<p:commandButton value="Volver" id="btnVolver" icon="ui-icon-close"
					oncomplete="PF('dlgComprobante').hide();" process="@this"
					styleClass="ui-priority-primary">
				</p:commandButton>
			</h:panelGrid>
		</h:form>
	</p:dialog>

	<p:dialog id="dlgReestablecerPassword"
		widgetVar="dlgReestablecerPassword"
		header="¿Olvidaste tu Usuario/Contraseña?" resizable="false"
		modal="true" closable="false">
		<h:form id="formReestablecerPass">
			<h:panelGrid id="panelReestablecesPass" columns="2">
				<h:outputLabel
					value="Ingrese su Usuario o e-mail asociado al mismo para recuperar su contraseña." />
				<p:inputText type="text" id="parametro"
					value="#{userView.parametro}" required="true"
					requiredMessage="No ingresó referencia para encontrar su cuenta.">
					<p:message for="parametro" display="icon" />
				</p:inputText>
			</h:panelGrid>

			<h:panelGrid id="panelBtn" columns="2">
				<p:commandButton id="btnConfirmar" value="Confirmar"
					update=":dlgLogin , :growl"
					actionListener="#{userView.reestablecerPassword}"
					icon="ui-icon-check">
					<p:confirm header="Confirmar Reestablecer Cuenta"
						message="Al confirmar se le enviará un e-mail con el nuevo password. La primera vez que ingrese con dicho password deberá cambiarlo por su seguridad."
						icon="ui-icon-alert" />
					<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
						<p:commandButton value="Aceptar" styleClass="ui-confirmdialog-yes"
							icon="ui-icon-check" />
						<p:commandButton value="Cancelar" type="button"
							styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
					</p:confirmDialog>
				</p:commandButton>
				<p:commandButton value="Cancelar" icon="ui-icon-close"
					process="@this" oncomplete="PF('dlgReestablecerPassword').hide()">
					<p:resetInput target=":dlgReestablecerPassword" />
				</p:commandButton>
			</h:panelGrid>
		</h:form>
	</p:dialog>
	<h:outputScript library="js/dist" name="menu.js" />
	<script>
		/**
		 * Slide right instantiation and action.
		 */
		var slideRight = new Menu({
			wrapper : '#o-wrapper',
			type : 'slide-right',
			menuOpenerClass : '.c-button',
			maskId : '#c-mask'
		});

		var slideRightBtn = document.querySelector('#c-button--slide-right');

		slideRightBtn.addEventListener('click', function(e) {
			e.preventDefault;
			slideRight.open();
		});
	</script>

	<script type="text/javascript">
		function handleLoginRequest(xhr, status, args) {
			if (args.validationFailed || !args.loggedIn) {
				PF('dlg').jq.effect("shake", {
					times : 5
				}, 100);
			} else {
				PF('dlg').hide();
				$('#loginLink').fadeOut();
				setTimeout(function() {
					window.location = args.view;
				}, 500);

			}
		}
	</script>
</h:body>

</html>

src/main/webapp/plantillas/combosAnidados.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>

	<h:form>
 		<p:panel header="" style="margin-bottom:10px;"><!-- Titulo del panel -->
			<h:panelGrid columns="2" cellpadding="5">
				<p:outputLabel for="" value="" /> <!-- Texto al lado del combo. for"" le pones el id del componente al que le pones el texto  -->
				<p:selectOneMenu id="" value="" 
					style="width:150px"> <!-- value = valor devuelto al seleccionar el combo  -->
					<p:ajax listener="" update="" /> <!-- en listener va el metodo que se ejecuta al ocurrir un evento. update lleva el id del componente que se va a actualizar en el xhtml  -->
					<f:selectItem itemLabel="" itemValue=""
						noSelectionOption="true" /> <!-- item label = valor mostrado en el combo al principio  -->
					<f:selectItems value="" /> <!-- value = lista de seect items del controlador valores mostrados en el combo  -->
				</p:selectOneMenu>

				<p:outputLabel for="" value="" />
				<p:selectOneMenu id="" value=""
					style="width:150px">
					<f:selectItem itemLabel="" itemValue=""
						noSelectionOption="true" />
					<f:selectItems value="" />
				</p:selectOneMenu>
			</h:panelGrid>
		</p:panel>

	</h:form>

</h:body>

</html>